# http://www.appveyor.com/docs/build-configuration

# version format
version: 1.0.{build}

# branches to build
branches:
  # whitelist
  only:
    - appveyor

# Build VM image
image: Visual Studio 2022

# scripts that are called at very beginning, before repo cloning
init:
  - echo Building Raptor for Windows
  - git config --global core.autocrlf input

# GIT clone directory
clone_folder: c:\projects\raptor

platform: x64
configuration: Release

cache:
  - C:\Tools\vcpkg\installed\

environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
  CYG_ROOT: C:/projects/cygwin64
  CYG_SETUP_URL: https://cygwin.com/setup-x86_64.exe
  CYG_MIRROR: https://cygwin.mirror.constant.com
  CYG_CACHE: C:/projects/cygwin64/var/cache/setup
  VCPKG_ROOT: C:/Tools/vcpkg
  DEST: "c:/projects/dest"
  CMAKE_GENERATOR_STRING: '"Visual Studio 17 2022"'

install:
  - cmd: 'git submodule update --init --recursive'
  - cmd: '%VCPKG_ROOT%/vcpkg.exe install libxml2:x64-windows'
  - ps:  New-Item -ItemType Directory -Force -Path $env:CYG_ROOT | Out-Null
  - ps:  echo "Installing Cygwin from $env:CYG_SETUP_URL to $env:CYG_ROOT/setup-x86_64.exe"
  - ps:  Invoke-WebRequest $env:CYG_SETUP_URL -OutFile $env:CYG_ROOT/setup-x86_64.exe
  - cmd: 'echo Installing Bison and Flex from Cygwin'
  - cmd: '%CYG_ROOT%\setup-x86_64.exe -qnNdO -R "%CYG_ROOT%" -s "%CYG_MIRROR%" -l "%CYG_CACHE%" -P bison,flex'
  - cmd: 'echo Check Cygwin setup'
  - cmd: '%CYG_ROOT%/bin/bash -lc "cygcheck -dc cygwin"'
  - cmd: 'echo Done setting up Cygwin'
  - cmd: '%CYG_ROOT%/bin/flex -V'
  - cmd: '%CYG_ROOT%/bin/bison --version'

before_build:
  - cmd: 'md c:\projects\dest'
  - cmd: 'md c:\projects\raptor\bld'
  - cmd: 'md c:\projects\raptor\bldstatic'

# custom build script
build_script:
  - cmd: 'cd c:\projects\raptor\bldstatic'
  - cmd: 'cmake -G %CMAKE_GENERATOR_STRING% -A x64 -DCMAKE_TOOLCHAIN_FILE=%VCPKG_ROOT%/scripts/buildsystems/vcpkg.cmake -DBISON_EXECUTABLE=%CYG_ROOT%/bin/bison -DFLEX_EXECUTABLE=%CYG_ROOT%/bin/flex -DCMAKE_INSTALL_PREFIX=%DEST%static ..'
  - cmd: 'cmake --build . --config Release --target INSTALL'
  - cmd: 'cd %DEST%static'
  - cmd: 'dir /s'
  - cmd: 'cd c:\projects\raptor\bld'
  - cmd: 'cmake -G %CMAKE_GENERATOR_STRING% -A x64 -DCMAKE_TOOLCHAIN_FILE=%VCPKG_ROOT%/scripts/buildsystems/vcpkg.cmake -DBISON_EXECUTABLE=%CYG_ROOT%/bin/bison -DFLEX_EXECUTABLE=%CYG_ROOT%/bin/flex -DBUILD_SHARED_LIBS:BOOL=ON -DCMAKE_INSTALL_PREFIX=%DEST% ..'
  - cmd: 'cmake --build . --config Release --target INSTALL'
  - cmd: 'cd %DEST%'
  - cmd: 'dir /s'
