.\"                                      Hey, EMACS: -*- nroff -*-
.\"
.\" rdfdump.1 - Raptor parser utility manual page
.\"
.\" $Id$
.\"
.\" Copyright (C) 2002 David Beckett - http://purl.org/net/dajobe/
.\" Institute for Learning and Research Technology - http://www.ilrt.org/
.\" University of Bristol - http://www.bristol.ac.uk/
.\"
.TH rdfdump 1 "2002-06-13"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
rdfdump \- Raptor RDF parser test program
.SH SYNOPSIS
.B rdfdump
.RI [ options ] source file: URI [base URI]
SH EXAMPLE
.IP
rdfdump -o ntriples file:data.rdf
.SH DESCRIPTION
This manual page documents the
.B rdfdump
command which is a test program for driving the parsers in
the
.B raptor
RDF parser library and emitting the generated triples.
.SH OPTIONS
rdfdump uses the usual GNU command line syntax, with long
options starting with two dashes (`-').
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-v, \-\-version
Show version of program.
.TP
.B \-n, \-\-ntriples
Parse N-Triples syntax, as defined in
.UR http://www.w3.org/TR/rdf-testcases/#ntriples
.UE
.TP
.B \-s, \-\-scan
Scan for <rdf:RDF> element in the RDF/XML source content..
.TP
.B \-a, \-\-assume
Assume the document is the RDF/XML (and rdf:RDF is optional).
.TP
.B \-r, \-\-replace-newlines
Replace newlines in multi-line literals with spaces.
.TP
.B \-q, \-\-quiet
No extra information messages.
.TP
.B \-o, \-\-output FORMAT
Set the output format to 'simple' (default) or 'ntriples'
.TP
.B \-v, \-\-version
Show version of program.
.SH SEE ALSO
.BR libraptor (7),
.BR \fIN-Triples\fR, 
.UR http://www.w3.org/TR/rdf-testcases/#ntriples
http://www.w3.org/TR/rdf-testcases/#ntriples
.UE
.SH AUTHOR
Dave Beckett - 
.UR http://purl.org/net/dajobe/
http://purl.org/net/dajobe/
.UE
