# -*- Mode: Makefile -*-
#
# Makefile.mkr - standalone file for Raptor mKR tests
#
# Copyright (C) 2014, Richard H. McCullough
# 
# This package is Free Software and part of Redland http://librdf.org/
# 
# It is licensed under the following three licenses as alternatives:
#   1. GNU Lesser General Public License (LGPL) V2.1 or any newer version
#   2. GNU General Public License (GPL) V2 or any newer version
#   3. Apache License, V2.0 or any newer version
# 
# You may not use this file except in compliance with at least one of
# the above three licenses.
# 
# See LICENSE.html or LICENSE.txt at the top of this package for the
# complete terms and further detail along with the license texts for
# the licenses in COPYING.LIB, COPYING and LICENSE-2.0.txt respectively.
# 
# 

RAPPER = rapper
RECHO = echo
RECHO_C = 
RECHO_N = -n
srcdir = .

TEST_SERIALIZE_FILES = \
rdfq-results.ttl rdf-schema.ttl rdfs-namespace.ttl \
test-07.ttl test-08.ttl test-16a.ttl \
test-28.ttl test-31.ttl test-32.ttl test-34.ttl

TEST_SERIALIZE_OUT_FILES = \
rdfq-results.mkr rdf-schema.mkr rdfs-namespace.mkr \
test-07.mkr test-08.mkr test-16a.mkr \
test-28-out.ttl test-31-out.ttl test-32-out.ttl test-34-out.ttl

# Used to make N-triples output consistent
BASE_URI = http://www.w3.org/2001/sw/DataAccess/df1/tests/
# for rdf-schema.ttl
RDF_NS_URI = http://www.w3.org/1999/02/22-rdf-syntax-ns
# for rdfs-namespace.ttl
RDFS_NS_URI = http://www.w3.org/2000/01/rdf-schema
ALL_TEST_FILES = README.txt \
	$(TEST_SERIALIZE_FILES) \
	$(TEST_SERIALIZE_OUT_FILES)

check-turtle-serialize-syntax:
	@set +e; result=0; \
	$(RECHO) "Testing mkr exact serialization output"; \
	for test in $(TEST_SERIALIZE_FILES); do \
	  name=`basename $$test .ttl` ; \
	  if test $$name = rdf-schema; then \
	    baseuri=$(RDF_NS_URI); \
	  elif test $$name = rdfs-namespace; then \
	    baseuri=$(RDFS_NS_URI); \
	  else \
	    baseuri=-; \
	  fi; \
	  $(RECHO) $(RECHO_N) "Checking $$test $(RECHO_C)"; \
	  $(RAPPER) -q -i turtle -o mkr $(srcdir)/$$test $$baseuri > $$name.out 2> $$name.err; \
	  cmp -s $(srcdir)/$$name.out $$name.mkr; \
	  status=$$?; \
	  if test $$status = 0; then \
	    $(RECHO) "ok"; \
	  else \
	    $(RECHO) "FAILED"; result=1; \
	    $(RECHO) $(RAPPER) -q -i turtle -o mkr $(srcdir)/$$test $$baseuri '>' $$name.out; \
	    cat $$name.err; \
	    diff -a -u $(srcdir)/$$name.out $$name.mkr; \
	  fi; \
	  rm -f $$name.out $$name.err; \
	done; \
	set -e; exit $$result

