.\"                                      Hey, EMACS: -*- nroff -*-
.\"
.\" rdfcat.1 - Raptor RDF Parser example code to merge rdf records
.\"
.\" Created by Sid Steward (http://accesspdf.com) for Creative Commons
.\" to simplify adding or changing records in RDF or Adobe XMP files.
.\"
.\" Copyright (C) 2002-2005 David Beckett - http://purl.org/net/dajobe/
.\" Institute for Learning and Research Technology - http://www.ilrt.bris.ac.uk/
.\" University of Bristol - http://www.bristol.ac.uk/
.\"
.TH rdfcat 1 "2005-10-24"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
rdfcat \- Raptor RDF cat utility
.SH SYNOPSIS
.B rdfcat
.RB [ OPTIONS ]
.IR "<filename>"
.IR "[<filename> ...]"
.br
Where \fI<filename>\fR may be a local filename, a URI, or \fB-\fR (stdin).  Files are parsed from left to right.
.SH EXAMPLES
.nf
rdfcat foo.rdf bar.rdf baz.rdf > foobarbaz.rdf
.br
rdfcat -spx CC_Attribution.xmp guide.xmp > guide.new.xmp
.br
rdfcat --base http://accesspdf.com/ my.rdf your.rdf > our.rdf
.SH DESCRIPTION
The \fBrdfcat\fR
utility parses RDF and RDF-formatted XMP, merging the triplets of input
files, optionally dropping duplicates.  When dropping duplicates, triplets
are keyed using subject + predicate.  When dropping duplicates, the triplet
parsed first is the only one output.  This is a simple minded means for
updating triplets in an RDF file.
.TP
Rdfcat is based on \fBrapper\fR, and shares many of its features.
.SH OPTIONS
.TP
.B \-h, \-\-help
Show a summary of the options.
.TP
.B \-i, \-\-input \fIFORMAT\fR
Set the input format to one of \fBrdfxml\fR (RDF/XML, \fIdefault\fR), \fBntriples\fR
(N-Triples, see below), \fBturtle\fR (Turtle, see below)
or \fBrss-tag-soup\fR (RSS Tag Soup).  The RSS Tag Soup parser
can turn the many XML RSS formats and Atom 0.3 into RDF triples.
.IP
The list of
parsers depends on how libraptor(3) was built.  The list of
supported parsers is given in the help summary given by \-h.
.TP
.B \-o, \-\-output \fIFORMAT\fR
Set the output format
to \fBrdfxml-abbrev\fR (RDF/XML with abbreviations, \fIdefault\fR), \fBntriples\fR
(N-Triples), \fBrdfxml\fR (RDF/XML), or \fBrss-1.0\fR (RSS 1.0, also an RDF/XML syntax).
.IP
The list of
serializers depends on how libraptor(3) was built.  The list of
supported serializers is given in the help summary given by \-h.
.TP
.B \-m, \-\-mode \fIMODE\fR
Set parser mode - \fBlax\fR (\fIdefault\fR) or \fBstrict\fR
.TP
.B \-e, \-\-ignore-errors
Ignore errors, do not emit the messages and try to continue parsing.
.TP
.B \-f, \-\-feature \fIFEATURE\fR[=\fIVALUE\fR]
Set a parser or serializer feature \fIFEATURE\fR
to \fIVALUE\fR, or to \fB1\fR if \fIVALUE\fR is omitted,
Use \fB\-f help\fR to get lists of valid parser and serializer features.
.IP
If the form \-f 'xmlns:\fIprefix\fP=\(dq\fIuri\fP\(dq' is used,
the prefix and namespace uri given will be set for serializing.
The syntax matches XML in that either or both of \fIprefix\fP
or \fIuri\fP can be omitted.
.TP
.B \-r, \-\-replace-newlines
Replace newlines in multi-line literals with spaces.
.TP
.B \-s, \-\-scan
Scan for <rdf:RDF> element in the RDF/XML source content.  This
is necessary when processing XMP files.
.TP
.B \-w, \-\-ignore-warnings
Ignore warnings, do not emit the messages.
.TP
.B \-v, \-\-version
Print the raptor version and exit.
.TP
.B \-b, \-\-base \fIURI\fR
Set the base URI to \fIURI\fR
.TP
.B \-d, \-\-drop-dup-preds
When two or more triplets have matching subject and predicate, keep only the triplet parsed first.  This option works only with the \fBrdfxml-abbrev\fR output serializer.
.TP
.B \-x, \-\-xmp
Format output for Adobe XMP.  This sets all subjects to the empty string. This option works only with the \fBrdfxml-abbrev\fR output serializer.
.SH SEE ALSO
rapper(1), libraptor(3), raptor-config(1)
.SH AUTHOR
Created by Sid Steward (ssteward@accesspdf.com) for Creative Commons.  Based on the rapper code by Dave Beckett.
